#+title: Java Tools
#+description: Readme file for Java Tools project

* Java Tools

Challenge: Make a set of useful tools so that you don't have to include any dependencies in your utility projects, and to make convenience APIs atop complicated Java classes.

*Tools*

- com.zentrope.tools.json.Parser

** Usage

This code is meant to be downloaded and inject into your own source code, not pulled in via a Maven-style dependency facility. The idea is that you pull in all this code, then delete the stuff you don't want.

** License

Copyright (c) 2020-present Keith Irwin

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see [http://www.gnu.org/licenses/](http://www.gnu.org/licenses/).
